[package]
name = "rust-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
rand = "0.8.5"

[lib]
name = "neural_network"
path = "src/neural_network/lib.rs"
